BASE_TEST_DIR=.

SRC_DIRS += \
	../reyes/src\
  ../matrix/test/helpers \
	../matrix/src\
	../reyes/test/helpers

TEST_SRC_DIRS += \
	../matrix/test/** \
	../reyes/test/**

INCLUDE_DIRS +=\
	../reyes/test/helpers \
	../reyes/inc \
  ../matrix/test/helpers \
	../matrix/inc 

include $(BASE_TEST_DIR)/MakefileBase.mk
