BASE_TEST_DIR=.

SRC_DIRS += \
	../reyes/src\
  ../matrix/test/helpers \
	../matrix/src\
	../reyes/test/helpers \
	../raytrace/src \
	../util/src \
	../raytrace/timing-tests/src

TEST_SRC_DIRS += \
	../matrix/test/** \
	../reyes/test/** \
	../raytrace/test/**

INCLUDE_DIRS +=\
	../reyes/test/helpers \
	../reyes/inc \
  ../matrix/test/helpers \
  ../raytrace/test/helpers \
  ../raytrace/test/mocks \
	../matrix/inc \
	../util/inc \
	../raytrace/inc \
	../raytrace/timing-tests/inc 

include $(BASE_TEST_DIR)/MakefileBase.mk
