BASE_TEST_DIR=../../test

SRC_DIRS += \
	../src\
	./helpers

TEST_SRC_DIRS += \
	.\
	./**

INCLUDE_DIRS +=\
	../inc \
	./helpers \
	../../test/cpputest/include/

include $(BASE_TEST_DIR)/MakefileBase.mk
