BASE_TEST_DIR=../../test

SRC_DIRS += \
	../src\
  ../../matrix/test/helpers \
	../../matrix/src\

TEST_SRC_DIRS += \
	./ \
	./**

INCLUDE_DIRS +=\
	../inc \
  ../../matrix/test/helpers \
  ../../reyes//test/helpers \
	../../matrix/inc \
	../../test/cpputest/include \
  ../../BasicRayTracer/BasicRayTracer

include $(BASE_TEST_DIR)/MakefileBase.mk
